// Get collection of all makes and models assocociated with them.

@host = localhost:5001
GET https://{{host}}/api/makes

POST https://{{host}}/api/vehicles
Content-Type: application/json" 

{
	"modelId": 1,
	"isRegistered": true,
	"contact": {
		"name": "name",
		"phone": "+380558887777",
		"email": "email@gmail.com"
	},
	"features": [3, 5]
}